[[redirects]]
  from = "https://disc.towerismmc.com"
  to = "https://towerismmc.com/help"
  status = 301
  force = true

[[redirects]]
  from = "https://vote.towerismmc.com"
  to = "https://towerismmc.com/help"
  status = 301
  force = true


[[redirects]]
  from = "https://help.towerismmc.com"
  to = "https://towerismmc.com/help"
  status = 301
  force = true
